 Merge all the NVDA twits to a csv file
 
 From 2013-04-11 to 2022-02-28

In [2]:
pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.59-py2.py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: pandas>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from yfinance) (2.2.5)
Requirement already satisfied: requests>=2.31 in /Users/q/Library/Python/3.13/lib/python/site-packages (from yfinance) (2.32.3)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.11-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/q/Library/Python/3.13/lib/python/site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from yfinance) (2025.2)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.6-py313-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.18.1.tar.gz (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 49.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/q/Library/Python/3.13/lib/python/site-packages (from yfinance) (4.13.3)
Collecting curl_cffi>=0.7 (from yfinance)
  Downloading curl_cffi-0.10.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (12 kB)
Collecting protobuf<6,>=5.29.0 (from yfinance)
  Downloading protobuf-5.29.4-cp38-abi3-macosx_10_9_universal2.whl.metadata (592 bytes)
Collecting websockets>=11.0 (from yfinance)
  Downloading websockets-15.0.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.8 kB)
Requirement already satisfied: soupsieve>1.2 in /Users/q/Library/Python/3.13/lib/python/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/q/Library/Python/3.13/lib/python/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.13.2)
Requirement already satisfied: cffi>=1.12.0 in /Users/q/Library/Python/3.13/lib/python/site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /Users/q/Library/Python/3.13/lib/python/site-packages (from curl_cffi>=0.7->yfinance) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/q/Library/Python/3.13/lib/python/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/q/Library/Python/3.13/lib/python/site-packages (from requests>=2.31->yfinance) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/q/Library/Python/3.13/lib/python/site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/q/Library/Python/3.13/lib/python/site-packages (from requests>=2.31->yfinance) (2.4.0)
Requirement already satisfied: pycparser in /Users/q/Library/Python/3.13/lib/python/site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.22)
Requirement already satisfied: six>=1.5 in /Users/q/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Downloading yfinance-0.2.59-py2.py3-none-any.whl (117 kB)
Downloading curl_cffi-0.10.0-cp39-abi3-macosx_11_0_arm64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 83.3 MB/s eta 0:00:00
Downloading frozendict-2.4.6-py313-none-any.whl (16 kB)
Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Downloading protobuf-5.29.4-cp38-abi3-macosx_10_9_universal2.whl (417 kB)
Downloading websockets-15.0.1-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.18.1-cp313-cp313-macosx_10_13_universal2.whl size=432805 sha256=acf9b97e99d82fce8ba6ab6defeadc161c1cb8a6d07ccee90f136cee557f1f77
  Stored in directory: /Users/q/Library/Caches/pip/wheels/91/08/75/7ec051c4c2b139cc4aa3a4ae6059d80900c301473b215aad59
Successfully built peewee
Installing collected packages: peewee, multitasking, websockets, protobuf, frozendict, curl_cffi, yfinance
Successfully installed curl_cffi-0.10.0 frozendict-2.4.6 multitasking-0.0.11 peewee-3.18.1 protobuf-5.29.4 websockets-15.0.1 yfinance-0.2.59

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import glob
import os
import yfinance as yf
import datetime

In [4]:
# Set the folder path containing CSV files
folder_path = '../2_data/NVDA_2013_2022/'  # Replace with your actual path

# Get all CSV file paths in the folder
csv_files = glob.glob(os.path.join(folder_path, '*.csv'))

# Initialize a list to hold DataFrames
df_list = []

# Read each CSV file and append to the list
for file in csv_files:
    try:
        df = pd.read_csv(file)
        df_list.append(df)
    except Exception as e:
        print(f"Failed to read {file}: {e}")

# Concatenate all DataFrames into one
combined_df = pd.concat(df_list, ignore_index=True)

# Convert 'created_at' column to datetime format (UTC)
combined_df['created_at'] = pd.to_datetime(combined_df['created_at'], utc=True)

# Sort the DataFrame by 'created_at' in descending order
combined_df.sort_values('created_at', ascending=True, inplace=True)


combined_df.head()

,Unnamed: 0,id,body,created_at,user,source,symbols,mentioned_users,entities,likes,links,conversation,reshare_message,reshares,owned_symbols,structurable
584180,14999,12994205,$NVDA shorts using a lot of ammo trying to kee...,2013-04-11 19:34:19+00:00,"{'id': 18393, 'username': 'fatcoin888', 'name'...","{'id': 1, 'title': 'Stocktwits', 'url': 'https...","[{'id': 2925, 'symbol': 'NVDA', 'title': 'NVID...",[],{'sentiment': None},NaN,NaN,NaN,NaN,NaN,NaN,NaN
584179,14998,12995313,"$NVDA quite a rebound today, i can hardly beli...",2013-04-11 20:03:53+00:00,"{'id': 37084, 'username': 'peter5slo', 'name':...","{'id': 1, 'title': 'Stocktwits', 'url': 'https...","[{'id': 2925, 'symbol': 'NVDA', 'title': 'NVID...",[],{'sentiment': None},NaN,NaN,NaN,NaN,NaN,NaN,NaN
584178,14997,12995587,As I said just over a week ago that $NVDA woul...,2013-04-11 20:12:52+00:00,"{'id': 27639, 'username': 'CDMCapital', 'name'...","{'id': 1, 'title': 'Stocktwits', 'url': 'https...","[{'id': 2925, 'symbol': 'NVDA', 'title': 'NVID...",[],{'sentiment': {'basic': 'Bullish'}},NaN,NaN,NaN,NaN,NaN,NaN,NaN
584177,14996,12995655,$NVDA shorting here is like picking up dimes i...,2013-04-11 20:15:08+00:00,"{'id': 27639, 'username': 'CDMCapital', 'name'...","{'id': 1, 'title': 'Stocktwits', 'url': 'https...","[{'id': 2925, 'symbol': 'NVDA', 'title': 'NVID...",[],{'sentiment': {'basic': 'Bullish'}},"{'total': 1, 'user_ids': [55546]}",NaN,NaN,NaN,NaN,NaN,NaN
584176,14995,12997231,Nvidia investing in â€˜once in a lifetime oppo...,2013-04-11 21:35:07+00:00,"{'id': 222797, 'username': 'StockTwitsLinks', ...","{'id': 1, 'title': 'Stocktwits', 'url': 'https...","[{'id': 2925, 'symbol': 'NVDA', 'title': 'NVID...",[],{'sentiment': None},NaN,"[{'title': ""Nvidia investing in 'once in a lif...",NaN,NaN,NaN,NaN,NaN

In [5]:
# Save the sorted DataFrame to a new CSV file
output_path = '../2_data/merged_nvda.csv'
combined_df.to_csv(output_path, index=False)

Get VIX and Stock Data 

Then merge to another CSV

In [6]:
# VIX data
vix_ticker = yf.Ticker("^VIX")

# Get today's date
today = datetime.date.today().strftime('%Y-%m-%d')

# Use the history method to fetch the data
vix_data = vix_ticker.history(start="2013-04-11", end="2022-02-28")

# Resetting the index to have Date as a column
vix_data = vix_data.reset_index()

# Selecting columns and converting column names to lowercase
vix_data = vix_data[['Date', 'Open', 'High', 'Low', 'Close']].copy()
vix_data.columns = ['date' if col == 'Date' else 'vix_' + col.lower() for col in vix_data.columns]  # Convert column names to lowercase

vix_data['date'] = vix_data['date'].dt.strftime('%Y-%m-%d')  # Ensure date is in the desired format

vix_data.head()

         date  vix_open  vix_high  vix_low  vix_close
0  2013-04-11     12.55     12.62    12.15      12.24
1  2013-04-12     12.61     13.12    11.99      12.06
2  2013-04-15     13.12     17.27    12.66      17.27
3  2013-04-16     14.72     14.87    13.91      13.96
4  2013-04-17     15.35     17.90    14.98      16.51

In [7]:
# NVDA data
nvda_ticker = yf.Ticker("NVDA")

# Get today's date
today = datetime.date.today().strftime('%Y-%m-%d')

# Use the history method to fetch the data
nvda_data = nvda_ticker.history(start="2013-04-11", end="2022-02-28")

# Resetting the index to have Date as a column
nvda_data = nvda_data.reset_index()

# Selecting columns and converting column names to lowercase
nvda_data = nvda_data[['Date', 'Open', 'High', 'Low', 'Close','Volume']].copy()
nvda_data.columns = ['date' if col == 'Date' else "nvda_" + col.lower() for col in nvda_data.columns]  # Convert column names to lowercase

nvda_data['date'] = nvda_data['date'].dt.strftime('%Y-%m-%d')  # Ensure date is in the desired format

nvda_data.head()

         date  nvda_open  nvda_high  nvda_low  nvda_close  nvda_volume
0  2013-04-11   0.293663   0.298306  0.285538    0.296449    969220000
1  2013-04-12   0.297842   0.307128  0.295288    0.303878    770548000
2  2013-04-15   0.302949   0.303877  0.295752    0.297609    430420000
3  2013-04-16   0.300395   0.302949  0.298770    0.300860    468844000
4  2013-04-17   0.298538   0.301324  0.295056    0.296913    532948000

In [8]:
# Merge vix_data and nvda_data on the 'date' column using inner join
merged_data = pd.merge(nvda_data, vix_data, on='date', how='inner')

merged_data.head()

,date,nvda_open,nvda_high,nvda_low,nvda_close,nvda_volume,vix_open,vix_high,vix_low,vix_close
0,2013-04-11,0.293663,0.298306,0.285538,0.296449,969220000,12.55,12.62,12.15,12.24
1,2013-04-12,0.297842,0.307128,0.295288,0.303878,770548000,12.61,13.12,11.99,12.06
2,2013-04-15,0.302949,0.303877,0.295752,0.297609,430420000,13.12,17.27,12.66,17.27
3,2013-04-16,0.300395,0.302949,0.298770,0.300860,468844000,14.72,14.87,13.91,13.96
4,2013-04-17,0.298538,0.301324,0.295056,0.296913,532948000,15.35,17.90,14.98,16.51

In [9]:
# Save the merged DataFrame to a new CSV file
output_path = '../2_data/merged_nvda_fin_data.csv'
combined_df.to_csv(output_path, index=False)